-- Backfill memories.inserted_at from the UUIDv7 id prefix (first 48 bits =
-- unix millis at insert). created_at is event-time and often backdated by
-- importers, so it cannot be used. One-off; new rows get DEFAULT now().
--
-- Run: psql -U nobrainr -d nobrainr -f 2026-06-11-inserted-at-backfill.sql

-- Unconditional: the UUIDv7 prefix is the true insert time for every row
-- (id is generated by the uuidv7() column default at insert), so this also
-- corrects rows the ALTER fast-defaulted to deploy-time now().
UPDATE memories
SET inserted_at = to_timestamp(
    (('x' || substr(replace(id::text, '-', ''), 1, 12))::bit(48)::bigint) / 1000.0
);

ANALYZE memories;
