"""Golden set v3 — abstention + contradiction + temporal-order (2026-07-22).

BEAM/LoCoMo-informed additions the v2 set lacks. Recall-only optimization
risks shipping confident fabrications — these rows measure the other side.

Three new abilities (tag synthetic-v3 + ability):
  abstention     — questions about facts that do NOT exist in the corpus.
                   Generated by LLM-perturbing a real memory (swap the
                   version/machine/tool to a plausible-but-false variant).
                   expected_ids = {{}} ; scored by _abstention_passes()
                   (top hit must stay under the confidence bar).
  contradiction  — mined from supersede chains (A superseded_by B): ask
                   about CURRENT state; expected = [B]. notes carries
                   negative_id=A so the breakdown can catch A-above-B.
  temporal-first — for an entity with a long memory span, ask for the
                   EARLIEST/original decision; expected = [oldest]. Tests
                   date-aware retrieval, not just similarity.

Run (in container, like v2):
    docker cp scripts/seed_golden_queries_v3.py <nb>:/tmp/seed3.py
    docker exec <nb> python3 /tmp/seed3.py --per-type 20 [--dry-run]
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import sys
from pathlib import Path

for c in [Path(__file__).resolve().parents[1] / "src", Path("/app/src"), Path("/app")]:
    if c.exists() and str(c) not in sys.path:
        sys.path.insert(0, str(c))
        break

from nobrainr.db.pool import get_pool  # noqa: E402
from nobrainr.extraction.llm import ollama_chat  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("seed_v3")

ABSTENTION_SCHEMA = {
    "type": "object",
    "properties": {"question": {"type": "string"}},
    "required": ["question"],
}

_ABSTENTION_SYSTEM = (
    "You write ONE search question about a fact that sounds plausible for "
    "this knowledge base but is NOT true in it. Take the real note below "
    "and perturb exactly one specific (a version, machine, port, tool, or "
    "outcome) into a variant that was never the case. The question must "
    "read like a normal recall query, name its subject explicitly, and be "
    "under 20 words. Do NOT ask about the real fact."
)

CONTRA_Q_SCHEMA = {
    "type": "object",
    "properties": {"question": {"type": "string"}},
    "required": ["question"],
}

_CONTRA_SYSTEM = (
    "You write ONE search question asking for the CURRENT state of the "
    "subject described in the note below. Phrase it so the answer is the "
    "note's content (the newest state), e.g. 'what is the current X for Y'. "
    "Under 18 words, subject named explicitly."
)

_TEMPORAL_SYSTEM = (
    "You write ONE search question asking for the EARLIEST or ORIGINAL "
    "decision/state about the subject in the note below — phrases like "
    "'what was the first', 'what did we originally'. The answer is this "
    "note (the oldest one). Under 18 words, subject named explicitly."
)


async def seed(per_type: int, dry_run: bool) -> None:
    pool = await get_pool()
    async with pool.acquire() as conn:
        existing = {
            r["query"].lower()
            for r in await conn.fetch("SELECT query FROM eval_golden_queries")
        }

    inserted = 0

    async def _insert(query: str, expected: list[str], ability: str, note: str) -> None:
        nonlocal inserted
        q = (query or "").strip()
        if not q or q.lower() in existing:
            return
        existing.add(q.lower())
        if dry_run:
            logger.info("[dry] %-14s %s -> %s", ability, q, expected or "ABSTAIN")
            inserted += 1
            return
        async with pool.acquire() as conn:
            await conn.execute(
                """
                INSERT INTO eval_golden_queries (query, expected_ids, notes, tags)
                VALUES ($1, $2::uuid[], $3, $4)
                """,
                q, expected, note, ["synthetic-v3", ability],
            )
        inserted += 1
        logger.info("[%3d] %-14s %s", inserted, ability, q)

    # ── abstention: perturb real high-trust memories into never-happened
    async with pool.acquire() as conn:
        seeds = await conn.fetch(
            """
            SELECT id, content, summary FROM memories
            WHERE superseded_by IS NULL AND length(content) BETWEEN 150 AND 1200
              AND claim_kind IN ('infra-state','code-state','incident-fix','design-decision')
              AND COALESCE(trust_score, 0) >= 0.7
            ORDER BY random() LIMIT $1
            """,
            per_type * 2,  # headroom for LLM failures/dupes
        )
    made = 0
    for s in seeds:
        if made >= per_type:
            break
        try:
            r = await ollama_chat(
                system=_ABSTENTION_SYSTEM,
                user=f"Real note:\n{s['content'][:900]}",
                schema=ABSTENTION_SCHEMA, temperature=0.6,
            )
        except Exception:
            continue
        q = (r or {}).get("question", "")
        if q:
            await _insert(q, [], "abstention",
                          f"perturbed from {s['id']} — fact does not exist")
            made += 1

    # ── contradiction: supersede chains, expected = the NEWER memory
    async with pool.acquire() as conn:
        chains = await conn.fetch(
            """
            SELECT old.id AS old_id, new.id AS new_id, new.content, new.summary
            FROM memories old
            JOIN memories new ON new.id = old.superseded_by
            WHERE new.superseded_by IS NULL
              AND length(new.content) BETWEEN 100 AND 1200
            ORDER BY new.updated_at DESC LIMIT $1
            """,
            per_type * 2,
        )
    made = 0
    for c in chains:
        if made >= per_type:
            break
        try:
            r = await ollama_chat(
                system=_CONTRA_SYSTEM,
                user=f"Note (newest state):\n{c['content'][:900]}",
                schema=CONTRA_Q_SCHEMA, temperature=0.4,
            )
        except Exception:
            continue
        q = (r or {}).get("question", "")
        if q:
            await _insert(q, [str(c["new_id"])], "contradiction",
                          f"negative_id={c['old_id']} (superseded — must NOT outrank)")
            made += 1

    # ── temporal-first: oldest memory of a long-span entity
    async with pool.acquire() as conn:
        spans = await conn.fetch(
            """
            SELECT e.canonical_name,
                   (ARRAY_AGG(m.id ORDER BY m.created_at ASC))[1] AS oldest_id,
                   (ARRAY_AGG(m.content ORDER BY m.created_at ASC))[1] AS oldest_content,
                   max(m.created_at) - min(m.created_at) AS span
            FROM entities e
            JOIN entity_memories em ON em.entity_id = e.id
            JOIN memories m ON m.id = em.memory_id AND m.superseded_by IS NULL
            GROUP BY e.id, e.canonical_name
            HAVING count(*) >= 5
               AND max(m.created_at) - min(m.created_at) > interval '30 days'
            ORDER BY random() LIMIT $1
            """,
            per_type * 2,
        )
    made = 0
    for s in spans:
        if made >= per_type:
            break
        if not s["oldest_content"] or len(s["oldest_content"]) < 80:
            continue
        try:
            r = await ollama_chat(
                system=_TEMPORAL_SYSTEM,
                user=(f"Subject: {s['canonical_name']}\n"
                      f"Note (the oldest):\n{s['oldest_content'][:900]}"),
                schema=CONTRA_Q_SCHEMA, temperature=0.4,
            )
        except Exception:
            continue
        q = (r or {}).get("question", "")
        if q:
            await _insert(q, [str(s["oldest_id"])], "temporal-first",
                          f"entity={s['canonical_name']} span={s['span']}")
            made += 1

    logger.info("DONE — inserted %d golden rows (dry_run=%s)", inserted, dry_run)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-type", type=int, default=20)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    asyncio.run(seed(args.per_type, args.dry_run))
