"""Category normalization — maps freeform categories to canonical set."""

CANONICAL_CATEGORIES = frozenset({
    "architecture",
    "debugging",
    "deployment",
    "infrastructure",
    "patterns",
    "tooling",
    "security",
    "frontend",
    "backend",
    "data",
    "business",
    "documentation",
    "session-log",
    "insight",
    "_archived",
})

# Maps known freeform categories to canonical ones.
# Unknown categories are normalized via heuristics (lowercase, strip).
_CATEGORY_MAP = {
    "learned-pattern": "patterns",
    "patterns": "patterns",
    "pattern": "patterns",
    "development_pattern": "patterns",
    "Patterns, Configurations, or Commands": "patterns",
    "Patterns, configurations, or commands that could be reused": "patterns",
    "Recipe Pattern": "patterns",
    "software development": "patterns",
    "Best Practices": "patterns",
    "tooling": "tooling",
    "scripting": "tooling",
    "Scripting": "tooling",
    "Command": "tooling",
    "tool": "tooling",
    "Knowledge Management": "tooling",
    "Code Review & Process Compliance": "tooling",
    "testing": "tooling",
    "Testing": "tooling",
    "asset management": "tooling",
    "dependency management": "tooling",
    "Software & Tools": "tooling",
    "Software": "tooling",
    "Tools": "tooling",
    "Visualization Libraries": "tooling",
    "Visualization": "tooling",
    "3D Modeling/Visualization": "tooling",
    "TouchDesigner Interface": "tooling",
    "PD/GEM Setup": "tooling",
    "infrastructure": "infrastructure",
    "system_configuration": "infrastructure",
    "system_optimization": "infrastructure",
    "Configuration": "infrastructure",
    "configuration": "infrastructure",
    "configuration_management": "infrastructure",
    "Config": "infrastructure",
    "technical_configuration": "infrastructure",
    "system_administration": "infrastructure",
    "system_customization": "infrastructure",
    "system_integration": "infrastructure",
    "map-configuration": "infrastructure",
    "icon-configuration": "infrastructure",
    "URL Configuration": "infrastructure",
    "integration": "infrastructure",
    "desktop-customization": "infrastructure",
    "System Administration": "infrastructure",
    "System Information": "infrastructure",
    "system_automation": "infrastructure",
    "Terminal Configuration": "infrastructure",
    "DevOps/Docker": "infrastructure",
    "Hardware": "infrastructure",
    "Hardware Components": "infrastructure",
    "Hardware/Architecture": "infrastructure",
    "Hardware/Connectors": "infrastructure",
    "Hardware Features": "infrastructure",
    "Hardware Integration": "infrastructure",
    "Hardware Limitations": "infrastructure",
    "Hardware Recommendation": "infrastructure",
    "Hardware Troubleshooting": "infrastructure",
    "Hardware Samplers": "infrastructure",
    "Connections": "infrastructure",
    "Repair/Electronics": "infrastructure",
    "Troubleshooting/Electronics": "debugging",
    "debugging": "debugging",
    "Debugging": "debugging",
    "gotchas": "debugging",
    "Solutions to Problems": "debugging",
    "Solutions to problems": "debugging",
    "solution": "debugging",
    "Solution": "debugging",
    "troubleshooting": "debugging",
    "Troubleshooting": "debugging",
    "Troubleshooting & Workarounds": "debugging",
    "Workflow/Troubleshooting": "debugging",
    "PD Debugging": "debugging",
    "Error Handling": "debugging",
    "Export Issues": "debugging",
    "Workaround": "debugging",
    "Streamlit Workarounds": "debugging",
    "frontend": "frontend",
    "Frontend": "frontend",
    "HTML": "frontend",
    "JavaScript": "frontend",
    "CSS": "frontend",
    "CSS Syntax": "frontend",
    "CSS Scaling": "frontend",
    "Responsive Design": "frontend",
    "styling": "frontend",
    "elementor": "frontend",
    "Font Management": "frontend",
    "HTML/CSS": "frontend",
    "HTML Meta Tags": "frontend",
    "user-preferences": "frontend",
    "frontend_development": "frontend",
    "Frontend Development - Viewer Functionality": "frontend",
    "Application Behavior": "frontend",
    "Viewer Behavior": "frontend",
    "insight": "insight",
    "instinct": "insight",
    "research": "insight",
    "contradiction": "insight",
    "general": "insight",
    "Technique": "insight",
    "Signal Processing": "insight",
    "Audio Processing": "insight",
    "Audio Processing & Visualization": "insight",
    "Audio Configuration": "insight",
    "Audio Engineering": "insight",
    "Audio Quality": "insight",
    "Audio Recording Techniques": "insight",
    "Sound Design/Dynamics": "insight",
    "Sound Design/Editing": "insight",
    "Rhythm/Pattern": "insight",
    "Rhythm/Groove": "insight",
    "Sequencing/Groove": "insight",
    "Effects": "insight",
    "Production Techniques": "insight",
    "architecture": "architecture",
    "Technical Decisions and Rationale": "architecture",
    "Technical decisions and their rationale": "architecture",
    "Technical Decision and Rationale": "architecture",
    "Architecture": "architecture",
    "Architecture & Workflow": "architecture",
    "Architecture/Feasibility": "architecture",
    "deployment": "deployment",
    "ops": "deployment",
    "business": "business",
    "personal": "business",
    "creative": "business",
    "project": "business",
    "productivity": "business",
    "strategy": "business",
    "Shipping/Logistics": "business",
    "Logistics/Shipping": "business",
    "Equipment/Maintenance": "business",
    "Equipment/Storage": "business",
    "Maintenance": "business",
    "Alternatives": "business",
    "Workflow & Execution": "business",
    "Workflow/Hardware Comparison": "business",
    "data": "data",
    "ml-training": "data",
    "labeling": "data",
    "Home Health Testing": "data",
    "GIS": "data",
    "GIS Processing": "data",
    "Geoprocessing": "data",
    "PostGIS": "data",
    "PostgreSQL": "data",
    "QGIS Print Composer": "tooling",
    "IFC Classes": "data",
    "data-visualization": "data",
    "Database": "data",
    "Biomarker Analysis": "data",
    "Biomass Analysis": "data",
    "geometry": "data",
    "Geometry Transformation": "data",
    "Ingredient Pairing": "data",
    "Ingredient Use": "data",
    "Data Analysis": "data",
    "Data Export": "data",
    "Data Ingestion": "data",
    "Data Interpretation": "data",
    "Data Management": "data",
    "Data Processing": "data",
    "Data Source": "data",
    "Data Storage & Backend": "data",
    "Data Synchronization": "data",
    "Data Validation/Coordinate Systems": "data",
    "Pandas": "data",
    "Raster Analysis": "data",
    "Raster Processing": "data",
    "Remote Sensing": "data",
    "Table Creation": "data",
    "SQL/Database Management": "data",
    "File Processing": "data",
    "File Formats": "data",
    "File Path Manipulation": "data",
    "Conversion/Data Transformation": "data",
    "Coordinate Systems": "data",
    "Coordinate Transformation": "data",
    "Regular Expressions": "data",
    "String Replacement": "data",
    "backend": "backend",
    "Drupal": "backend",
    "URL Construction": "backend",
    "module": "backend",
    "technical development": "backend",
    "Performance Optimization": "backend",
    "Performance": "backend",
    "Implementation": "backend",
    "Code Example": "backend",
    "Code Structure": "backend",
    "code_refinement": "backend",
    "Technical Implementation": "backend",
    "Software Development": "backend",
    "Scripting/Development Workflow": "backend",
    "documentation": "documentation",
    "project-docs": "documentation",
    "reference": "documentation",
    "technical documentation improvement": "documentation",
    "documentation & setup optimization": "documentation",
    "documentation_refinement": "documentation",
    "Documentation & Iteration": "documentation",
    "session-log": "session-log",
    "development_activity": "session-log",
    "development_workflow": "session-log",
    "system development": "session-log",
    "project_understanding": "session-log",
    "environment_management, knowledge_management": "tooling",
    "environment_management, memory_management": "tooling",
    "Verification": "debugging",
    "verification": "debugging",
    "Git": "tooling",
    "git": "tooling",
    "PHP/WordPress Development": "backend",
    "php/wordpress development": "backend",
    "WordPress Development": "backend",
    "wordpress development": "backend",
    "Automation & Scripting": "tooling",
    "automation & scripting": "tooling",
    "security": "security",
    "_archived": "_archived",
}


def normalize_category(category: str | None) -> str | None:
    """Normalize a category string to a canonical value.

    Returns None if input is None.
    Known categories are mapped via case-insensitive lookup.
    Unknown categories use heuristic matching.
    """
    if category is None:
        return None
    # Direct lookup (exact case)
    canonical = _CATEGORY_MAP.get(category)
    if canonical:
        return canonical
    # Case-insensitive lookup
    lower = category.lower().strip()
    if lower in CANONICAL_CATEGORIES:
        return lower
    # Try case-insensitive map lookup
    if not hasattr(normalize_category, "_lower_map"):
        normalize_category._lower_map = {k.lower(): v for k, v in _CATEGORY_MAP.items()}
    canonical = normalize_category._lower_map.get(lower)
    if canonical:
        return canonical
    # Heuristic: check if any canonical category is a substring
    for canon in CANONICAL_CATEGORIES:
        if canon in lower:
            return canon

    # Return lowercased — will be visible in stats as uncategorized
    return lower
